#ifdef LORAMAC_IS_ROOT
#define UIP_FALLBACK_INTERFACE         loramac_interface
#endif

#ifdef LOG_LEVEL_LORAPHY_CONF
#define LOG_LEVEL_LORAPHY LOG_LEVEL_LORAPHY_CONF
#else
#define LOG_LEVEL_LORAPHY LOG_LEVEL_NONE
#endif

#ifdef LOG_LEVEL_LORAMAC_CONF
#define LOG_LEVEL_LORAMAC LOG_LEVEL_LORAMAC_CONF
#else
#define LOG_LEVEL_LORAMAC LOG_LEVEL_NONE
#endif

#ifdef LOG_LEVEL_LORABRIDGE_CONF
#define LOG_LEVEL_LORABRIDGE LOG_LEVEL_LORABRIDGE_CONF
#else
#define LOG_LEVEL_LORABRIDGE LOG_LEVEL_NONE
#endif
